name: Doc Check
on: [pull_request, push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: debug tree before
      run: tree
    - name: install dependencies
      run: |
        pip install -e .[examples,examples_unix]
        pip install sphinx-gallery sphinx_bootstrap_theme numpydoc
    - name: build docs
      run: |
        cd doc
        make html
    - name: debug tree
      run: tree
    - name: pull latest docs
      run: |
        git clone https://github.com/openml/openml-python.git --branch gh-pages --single-branch
    - name: last tree
      run: tree
